name: "Set CI tools"
description: "Basic CI tools in your GitHub Action"
author: "pampatzoglou"
inputs:
  helm-version:  # id of input
    description: 'version of helm'
    required: true
    default: 'v3.5.0'
  helmfile-version:  # id of input
    description: 'version of helmfile'
    required: true
    default: 'v0.137.0'
  yq-version:  # id of input
    description: 'version of yq'
    required: true
    default: 'v0.137.0'
  az-version:  # id of input
    description: 'version of az'
    required: true
    default: '2.17.1'        
runs:
  using: "node12"
  main: "lib/main.js"