name: "Build and test Action"
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "npm install"
        run: npm install

      - name: "npm run build"
        run: npm run build

      - name: "npm test"
        run: npm test

      - name: "npm audit"
        run: npm audit