name: DELETE ENV
on: 
  delete:
    branches-ignore:
    - main
    - master

jobs:
  delete-multistage:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
