name: DEPLOY TO PRODUCTION
on:
  push:
    tags:
    - '*'
jobs:
  container-job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - run: echo "DEPLOY TO PRODUCTION"

