name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "npm install"
        run: npm install
      - name: "npm run build"
        run: npm run build
      - uses: ./
      - name: Testing
        run: |
          helm version